ft: bash
name: '*nix'
keywords: 
  - unix
  - linux
  - bsd
  - linux команды
  - команды ubuntu
  - команды debian
  - команды ssh
  - ssh примеры
  - примеры unix
  - примеры linux
  - примеры bsd
links: 
  - [http://www.opennet.ru/tips/sml/, 'много интересных заметок на разные темы']
  - [http://www.linuxselfhelp.com/, 'большой сборник документаций']
  - [https://www.pcwdld.com/bash-cheat-sheet, 'cheat-sheet по bash']
